use_frameworks!
pod 'feathers-ios', :path => '../'
pod 'feathers-ios/Rest', :path => '../'
pod 'feathers-ios/Socket', :path => '../'
pod 'feathers-ios/ObjectMapper', :path => '../'
pod 'feathers-ios/ReactiveCocoa', :path => '../'
target 'feathers-ios_Tests' do
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
